### ISSUE TITLE
action.ts doesn't process jsonPath from yml script.  it defaults to 'total.statements.pct' in badges.ts

### ISSUE THREAD

**Issue by TimSVector** [jaywcjlove/coverage-badges-cli#31]
No jsonPath processing in *action.ts*.  It always defaults to  'total.statements.pct' from badges.ts.

Fix should be easy:

Add to *actions.ts* :
    `const jsonPath = getInput('jsonPath') || 'total.statements.pct';`

Modify in *actions.ts*
    `const svgStr = badge({ label, style, jsonPath } as BadgeOption, sourceData);`

**Comment by jaywcjlove** [comment]
@TimSVector thx!
